server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

# h2
spring:
  datasource:
    url: jdbc:h2:mem:kpsecdb;MODE=MySQL
    platform: h2
    username: kpsec
    password: kpsec
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
  
  #devtool      
  devtools:
    livereload:
      enabled: true